name: Development deployments

on:
  release:
    types: [published]

jobs:
  docker-push:
    name: Push docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push BackEndApp image
        id: backend_docker_build
        uses: docker/build-push-action@v2
        with:
          context: BackEndApp/
          tags: autodlhub/backend:${{ github.ref }}
          push: true

      - name: Build and push FrontEndApp image
        id: frontend_docker_build
        uses: docker/build-push-action@v2
        with:
          context: FrontEndApp/v1-react/
          tags: autodlhub/frontend:${{ github.ref }}
          push: true
